// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAllServers() {
  return window['go']['main']['App']['CheckAllServers']();
}

export function CheckCluster(arg1) {
  return window['go']['main']['App']['CheckCluster'](arg1);
}

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function CollectServerMetrics(arg1) {
  return window['go']['main']['App']['CollectServerMetrics'](arg1);
}

export function CreateCluster(arg1) {
  return window['go']['main']['App']['CreateCluster'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteAlert(arg1) {
  return window['go']['main']['App']['DeleteAlert'](arg1);
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetMetricsHistory(arg1, arg2) {
  return window['go']['main']['App']['GetMetricsHistory'](arg1, arg2);
}

export function ListAlerts(arg1) {
  return window['go']['main']['App']['ListAlerts'](arg1);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function MarkAlertRead(arg1) {
  return window['go']['main']['App']['MarkAlertRead'](arg1);
}

export function Notify(arg1) {
  return window['go']['main']['App']['Notify'](arg1);
}

export function UpdateCluster(arg1) {
  return window['go']['main']['App']['UpdateCluster'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
