// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {domain} from '../models';

export function CheckAllServers():Promise<Array<main.ServerDTO>>;

export function CheckCluster(arg1:string):Promise<Array<main.ServerDTO>>;

export function CheckServer(arg1:string):Promise<main.ServerDTO>;

export function CollectServerMetrics(arg1:string):Promise<main.ServerDTO>;

export function CreateCluster(arg1:main.ClusterInputDTO):Promise<main.ClusterDTO>;

export function CreateServer(arg1:main.ServerInputDTO):Promise<main.ServerDTO>;

export function DeleteAlert(arg1:string):Promise<void>;

export function DeleteCluster(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetDashboardStats():Promise<main.DashboardStatsDTO>;

export function GetMetricsHistory(arg1:string,arg2:number):Promise<Array<main.MetricsSampleDTO>>;

export function ListAlerts(arg1:number):Promise<Array<main.AlertDTO>>;

export function ListClusters():Promise<Array<main.ClusterSummaryDTO>>;

export function ListServers():Promise<Array<main.ServerDTO>>;

export function MarkAlertRead(arg1:string):Promise<void>;

export function Notify(arg1:domain.Alert):Promise<void>;

export function UpdateCluster(arg1:main.ClusterInputDTO):Promise<main.ClusterDTO>;

export function UpdateServer(arg1:main.ServerInputDTO):Promise<main.ServerDTO>;
